### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by laikadoggirl** [Vaerys-Dawn/DiscordSailv2#1]
I was told to install this 
1. Build with maven
2. Find and edit config file
3. Run
Can someone give me more detail on how to install this?

**Comment by Vaerys-Dawn** [comment]
Hey so while you could build and use it i wouldn't  recommend it at this time because if you wish to customise some of its features you need.to edit it's base code. In the future i plan to have a config.json that you can edit in order to change things like bot username and other things of the likes.

**Comment by laikadoggirl** [comment]
When I eventually go to how would I install it then? Thanks.

**Comment by Vaerys-Dawn** [comment]
It may not be for a while, if you contact me on discord @Dawn Felstar#1235 i may be able to get the bot on your server but as sail is still sorta in development and still needs a lot of work put into it it may take a while before it is ready for public distribution.
